import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import profile from "@/app/(assets)/profile.svg";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between my-16 mx-16">
          <div className="w-12"></div>
          <h1 className="text-5xl font-bold">Winner Dinner</h1>
          <div>
            <Image src={profile} alt="profile" />
          </div>
        </header>
        {children}
        <footer className="fixed bottom-0 right-0">
          <h4>Created by Adam Hale</h4>
        </footer>
      </body>
    </html>
  );
}
